config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :meetings
  resources :action_items
  resources :agenda_items
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'pages#main'
  get '/test01/', to: 'pages#main'
end

app/models/agenda_item.rb
class AgendaItem < ApplicationRecord
  belongs_to :user
  belongs_to :meeting
  has_many :comments, :as => :commentable

end

app/controllers/agenda_items_controller.rb
class AgendaItemsController < ApplicationController
  before_action :set_agenda_item, only: [:show, :edit, :update, :destroy]

  # GET /agenda_items
  # GET /agenda_items.json
  def index
    @agenda_items = AgendaItem.all
  end

  # GET /agenda_items/1
  # GET /agenda_items/1.json
  def show
  end

  # GET /agenda_items/new
  def new
    @agenda_item = AgendaItem.new
  end

  # GET /agenda_items/1/edit
  def edit
  end

  # POST /agenda_items
  # POST /agenda_items.json
  def create
    @agenda_item = AgendaItem.new(agenda_item_params)

    respond_to do |format|
      if @agenda_item.save
        format.html { redirect_to @agenda_item, notice: 'Agenda item was successfully created.' }
        format.json { render :show, status: :created, location: @agenda_item }
      else
        format.html { render :new }
        format.json { render json: @agenda_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agenda_items/1
  # PATCH/PUT /agenda_items/1.json
  def update
    respond_to do |format|
      if @agenda_item.update(agenda_item_params)
        format.html { redirect_to @agenda_item, notice: 'Agenda item was successfully updated.' }
        format.json { render :show, status: :ok, location: @agenda_item }
      else
        format.html { render :edit }
        format.json { render json: @agenda_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agenda_items/1
  # DELETE /agenda_items/1.json
  def destroy
    @agenda_item.destroy
    respond_to do |format|
      format.html { redirect_to agenda_items_url, notice: 'Agenda item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agenda_item
      @agenda_item = AgendaItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def agenda_item_params
      params.require(:agenda_item).permit(:title)
    end
end

app/helpers/agenda_items_helper.rb
module AgendaItemsHelper
end

app/views/agenda_items/_form.html.erb
<%= form_with(model: agenda_item, local: true) do |form| %>
  <% if agenda_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(agenda_item.errors.count, "error") %> prohibited this agenda_item from being saved:</h2>

      <ul>
      <% agenda_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :agenda_item_title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/agenda_items/edit.html.erb
<h1>Editing Agenda Item</h1>

<%= render 'form', agenda_item: @agenda_item %>

<%= link_to 'Show', @agenda_item %> |
<%= link_to 'Back', agenda_items_path %>

app/views/agenda_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Agenda Items</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @agenda_items.each do |agenda_item| %>
      <tr>
        <td><%= agenda_item.title %></td>
        <td><%= link_to 'Show', agenda_item %></td>
        <td><%= link_to 'Edit', edit_agenda_item_path(agenda_item) %></td>
        <td><%= link_to 'Destroy', agenda_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Agenda Item', new_agenda_item_path %>

app/views/agenda_items/new.html.erb
<h1>New Agenda Item</h1>

<%= render 'form', agenda_item: @agenda_item %>

<%= link_to 'Back', agenda_items_path %>

app/views/agenda_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @agenda_item.title %>
</p>

<%= link_to 'Edit', edit_agenda_item_path(@agenda_item) %> |
<%= link_to 'Back', agenda_items_path %>