config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :meetings
  resources :action_items
  resources :agenda_items
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'pages#main'
  get '/test01/', to: 'pages#main'
end

app/models/action_item.rb
class ActionItem < ApplicationRecord
  belongs_to :user
  belongs_to :meeting
  has_many :comments, :as => :commentable
end

app/controllers/action_items_controller.rb
class ActionItemsController < ApplicationController
  before_action :set_action_item, only: [:show, :edit, :update, :destroy]

  # GET /action_items
  # GET /action_items.json
  def index
    @action_items = ActionItem.all
  end

  # GET /action_items/1
  # GET /action_items/1.json
  def show
  end

  # GET /action_items/new
  def new
    @action_item = ActionItem.new
  end

  # GET /action_items/1/edit
  def edit
  end

  # POST /action_items
  # POST /action_items.json
  def create
    @action_item = ActionItem.new(action_item_params)

    respond_to do |format|
      if @action_item.save
        format.html { redirect_to @action_item, notice: 'Action item was successfully created.' }
        format.json { render :show, status: :created, location: @action_item }
      else
        format.html { render :new }
        format.json { render json: @action_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /action_items/1
  # PATCH/PUT /action_items/1.json
  def update
    respond_to do |format|
      if @action_item.update(action_item_params)
        format.html { redirect_to @action_item, notice: 'Action item was successfully updated.' }
        format.json { render :show, status: :ok, location: @action_item }
      else
        format.html { render :edit }
        format.json { render json: @action_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /action_items/1
  # DELETE /action_items/1.json
  def destroy
    @action_item.destroy
    respond_to do |format|
      format.html { redirect_to action_items_url, notice: 'Action item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_action_item
      @action_item = ActionItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def action_item_params
      params.require(:action_item).permit(:title)
    end
end

app/helpers/action_items_helper.rb
module ActionItemsHelper
end

app/views/action_items/_form.html.erb
<%= form_with(model: action_item, local: true) do |form| %>
  <% if action_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(action_item.errors.count, "error") %> prohibited this action_item from being saved:</h2>

      <ul>
      <% action_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :action_item_title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/action_items/edit.html.erb
<h1>Editing Action Item</h1>

<%= render 'form', action_item: @action_item %>

<%= link_to 'Show', @action_item %> |
<%= link_to 'Back', action_items_path %>

app/views/action_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Action Items</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @action_items.each do |action_item| %>
      <tr>
        <td><%= action_item.title %></td>
        <td><%= link_to 'Show', action_item %></td>
        <td><%= link_to 'Edit', edit_action_item_path(action_item) %></td>
        <td><%= link_to 'Destroy', action_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Action Item', new_action_item_path %>

app/views/action_items/new.html.erb
<h1>New Action Item</h1>

<%= render 'form', action_item: @action_item %>

<%= link_to 'Back', action_items_path %>

app/views/action_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @action_item.title %>
</p>

<%= link_to 'Edit', edit_action_item_path(@action_item) %> |
<%= link_to 'Back', action_items_path %>